Add linter action
TritonSE/SDCTA-Data-Visualization-Website pull request #23
Opened 2023-02-25 20:36 UTC by NirmalAgnihotri

### Tracking Info

Resolves #<issue number>

Make sure your branch name conforms to: `<feature|staging|bugfix|...>/<username>/<3-4 word description separated by dashes>`. Otherwise, please rename your branch and create a new PR.

### Changes

What changes did you make?

- Added linting on push action
### Testing

How did you confirm your changes worked? 

- TODO

### Confirmation of Change 

Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

TODO...

2023-02-26 23:43 UTC, vs2961 requested changes
Your github action seems to be failing, perhaps because this was done on a branch where eslint wasn't installed? In any case, I'd recommend merging this PR with #24 because they are pretty similar changes.

2023-02-27 02:37 UTC, vs2961 approved these changes
lgtm, if something changed in the other files I'll probably never catch it anyways so very good!

2023-02-27 02:37 UTC, vs2961 commented on server/.eslintrc.json
> +    // Disable rules that conflict with Mongo
These rules work for me!

2023-02-27 02:37 UTC, vs2961 commented on SDCTA/.eslintrc.json
> +  "plugins": ["react"],
Honestly don't know what the correct rules to ignore are for the frontend, so I'll leave that to someone working on a frontend team.

2023-03-01 22:26 UTC, Anthonyp0329 approved these changes

2023-03-01 22:26 UTC, Anthonyp0329 commented on SDCTA/.eslintrc.json
> +        }
Rules look good to me! Can also change as we go if necessary

2023-03-01 22:33 UTC, merged