Feature/miyuki l/individual visualization page
TritonSE/SDCTA-Data-Visualization-Website pull request #26
Opened 2023-02-28 04:24 UTC by Miyuki-L

### Tracking Info

Resolves #9 

Make sure your branch name conforms to: `<feature|staging|bugfix|...>/<username>/<3-4 word description separated by dashes>`. Otherwise, please rename your branch and create a new PR.

### Changes

What changes did you make?

- Built the Invidual Data Visualization page

### Testing

How did you confirm your changes worked? 

- Tested Rending page on different screens. 

### Confirmation of Change 

Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

![image](https://user-images.githubusercontent.com/59126064/221753157-7c7e7126-e1ac-4e78-851a-4b2d3d2cdd19.png)
![image](https://user-images.githubusercontent.com/59126064/221753189-24b75b58-1b19-4ecd-b411-23be459991e5.png)

2023-03-16 15:59 UTC, vs2961 requested changes
It's strange that github is showing that you made changes to the server/ folder, and this is likely because you merged from the backend category branch instead of main. To avoid any unintentional changes to the backend, I would suggest that you run `git checkout main -- server/` from the root folder of this repo.

2023-03-16 15:59 UTC, vs2961 commented on .DS_Store
This file should not be here, it's ignored in the gitignore so once you remove it, it won't be pushed back.

2023-03-30 05:38 UTC, NirmalAgnihotri approved these changes
Approving now, good job on the individual viz component

2023-03-30 05:38 UTC, NirmalAgnihotri commented on SDCTA/src/pages/IndividualVisualization.tsx
> +import backIcon from "./backIcon.svg";
Component looks great, good job guys!

2023-03-30 05:40 UTC, NirmalAgnihotri commented on .DS_Store
Removed it

2023-03-30 05:46 UTC, NirmalAgnihotri commented on .DS_Store
It looks like everything is in line with main for server/, so I think the changes are more because of formatting and linting. In any case, we'll merge in the backend branch after this so it'll be fine in the end.

2023-03-30 14:13 UTC, vs2961 approved these changes
Looks good! Great work!

2023-03-30 21:25 UTC, merged