Schema change + function to updateUserDetails
TritonSE/SDCTA-Data-Visualization-Website pull request #36
Opened 2023-04-17 21:59 UTC by Anthonyp0329

### Tracking Info

Resolves #<issue number>

Make sure your branch name conforms to: `<feature|staging|bugfix|...>/<username>/<3-4 word description separated by dashes>`. Otherwise, please rename your branch and create a new PR.

### Changes

What changes did you make?

Made changes to user schema, also made a function in consumer.ts called updateUserDetails that takes in details and updates a user by email with them. 

To call this function, use this import:
import { auth } from "../../firebase-config";

Then, for the email field in the function, can pass in auth.currentUser.email.
If the user isn't logged in, this will be null however, so make sure to check for that. 

Here's an example of how I called this function:

`let email;
      if (auth.currentUser == null) {
        navigate("/Signup");
        return;
      } else {
        email = auth.currentUser.email;
      }
      if (email == null) {
        navigate("/Signup");
        return;
      } else {
        await updateUserDetails(
          phoneNumber,
          address,
          city,
          state,
          zipCode,
          country,
          email
        );
`

The function in consumer.ts needs to be changed to have additional input fields, as well as the user schema

### Testing

How did you confirm your changes worked?

Used this method to update a user's details.

### Confirmation of Change

Upload a screenshot, if possible. Otherwise, please provide instructions on how to see the change.

TODO...

2023-04-18 18:33 UTC, wllmwu commented
@Anthonyp0329 fyi you can use a triple backtick to create a code block:

```javascript
      let email;
      if (auth.currentUser == null) {
        navigate("/Signup");
        return;
      } else {
        email = auth.currentUser.email;
      }
      if (email == null) {
        navigate("/Signup");
        return;
      } else {
        await updateUserDetails(
          phoneNumber,
          address,
          city,
          state,
          zipCode,
          country,
          email
        );
```

2023-04-24 21:54 UTC, NirmalAgnihotri requested changes

2023-04-24 21:54 UTC, NirmalAgnihotri commented on SDCTA/src/api/consumer.ts
> +  phoneIn: string,
Can we encapsulate all of this info in an object? I think that will make this easier to call

2023-04-24 21:54 UTC, NirmalAgnihotri commented on SDCTA/src/api/consumer.ts
> +  phoneIn: string,
If we do that, we can make the type that this function takes only optionally require these fields so we can do updates where we don't need to update all of these details at the same time. So you can make the type something like this:
```
type userDetails = {
  emailIn:
  phoneIn?:
  stateIn?:
  ...
} 
```
Note that the email is required since it's needed to make the call to get their id. The other fields have a "?" since they're not required.

2023-04-24 21:54 UTC, NirmalAgnihotri commented on SDCTA/src/api/consumer.ts
> +  let response = await fetch(
This fetch gets the user's details. We can make this its own function in consumer.ts. Then, in here just call that function to get the id.

2023-04-24 21:54 UTC, NirmalAgnihotri commented on SDCTA/src/api/consumer.ts
> +    const id = result._id;
Change so one call with email

2023-05-01 20:04 UTC, SamvritSrinath approved these changes

2023-05-01 21:48 UTC, NirmalAgnihotri approved these changes

2023-05-01 21:49 UTC, merged